### ISSUE TITLE
Missing file in npm package: default-background.jpg

### ISSUE THREAD

**Issue by rozenmd** [andrioid/gatsby-plugin-social-cards#2]
Hey Andri, 

Just getting this error when running the latest npm package:

`Error: ENOENT: no such file or directory, open '<MY_DIR>/node_modules/gatsby-plugin-social-cards/src/default-background.jpg'`

I'm guessing it didn't get bundled?

**Comment by andrioid** [comment]
Hey Max

You're right, the default background image wasn't bundled and I never noticed because I had my own default configured in gatsby-config.js.

In version 0.5.14 I have moved the default-background into img/ where it will be shipped with the npm package.

Thanks for reporting. Let me know if it doesn't work.
